import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import ClientLayout from "@/components/layout/client-layout";
import { CookiesProvider } from "next-client-cookies/server";
import clientPromise from "@/lib/mongodb";
import { ObjectId } from "mongodb";
const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "NextFit",
	description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    const cookieStore = await cookies();
    const theme = cookieStore.get('theme')?.value ?? 'dark';

    const client = await clientPromise;
    const users = client.db("nextfit").collection("users");

    // Here we login the user automatically if they are logged in
    // We pass it to the client afterwards
    const userId = cookieStore.get('user').value;
    const user = await users.findOne({ _id: new ObjectId(userId) });
    user._id = undefined;

	return <CookiesProvider>
        <html lang="en" className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <body className={theme}>
                <div className="relative min-h-screen flex flex-col">
                    <ClientLayout theme={theme} user={user}>
                        { children }
                    </ClientLayout>
                </div>
            </body>
        </html>
    </CookiesProvider>;
}
